language: node_js
node_js: '10'
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install: yarn install
script:
- yarn test
- CI=false yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  project: light-service
  token:
    secure: JyLXfzZoR6ToEf4I9BwMAPEGBhRCnEZ5mwNSStybBqXqya0kDWsuNiLN4dpzOJBURes6zUb/7ty9tHXBMfRVh9xAwYHA46ZymbJaRDRTfOHUWOVhcVYfGK8GqwcU/sTfbxmgGdU5XtZ+6H4mZ1BtD/wDlD+51VmA8WJFKxifHWYOpJwBF4bbZlPr1Z2JFPJG3FFTB7Yx6K4wIPkSCLQAKyJdMxu6VRco+r8KU9Prf+Dy6abrfF3Et4K6gu7Cz85ql7yM5SKQP+8NmanBhTsMgTY5n49nZ23j8kpB2SPzO7Rqd5K3Y+7HGDlOL0tyXw76RLuGwu/xyIec2tWdZajLJnjmfhDBCuE77yB/p4HbM8npoPpGgziHnHZ1ZNDK2sjT+jdO8nbN2EQno9UjchHQuBd5ag3eCbc4lq+liHByvEeE1Jy1rFIGULUcag20L2g5fE0NbPlVjyv+SQrs/LJkqU5Klgg2wD8jcWS9b44tbnU55tF1oTr1mlnRrR2sSS5oqe8Iqx05t9E22FayTgDP+fA3+OA/3XoUO6d1h3cach2dQuKxkAQxqCU/Em7fnjlsAPqV8pNFSvmJsUmIorA39lmHbIv5s2PP3rYdNEvi/IxFsRy5VGXQ7vB+tKd3To8tKYkdMLJxEAZO2EGcKuoQiRSmI/c6K2QBPM9YIoEzods=
branches:
  only:
  - master
